### ISSUE TITLE
例外を適切な std::exception ベースへ

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#11]
https://github.com/sapporocpp/othello-battler/blob/master/othello_lib.hpp#L13

``` c++
    class InvalidArgumentException{
```

↓こんな感じ？

``` c++
class InvalidArgumentException: public std::invalid_argument{
```

しかし、実質中身は特になさそうなので、これを使っているところは素直に`std::invalid_argument`をthrowすればいいかも。

**Comment by ignisan** [comment]
try-catchが見当たらない？

**Comment by maraigue** [comment]
事情としては以下の通りでした。
- catchをユーザコード側（othello_sample.cpp）で行うことを想定し、別の例外クラスを作っていた
- ただ、この例外は本当に例外的なので（othello_runner.cppが不正なコマンドライン引数を送った場合にのみ起きる）、catchを書くとユーザコードが煩雑になると思って書いていなかった

ただ、catchをライブラリ内で行う仕様に変更したため、この問題を気にすることがなくなりました。例外についても単に`std::invalid_argument`を投げるようにしてあります。

**Comment by maraigue** [comment]
https://github.com/sapporocpp/othello-battler/commit/a7a080d7becc60a5a8ed49bc20d786b4d4db1808 にて対応しました。
