### ISSUE TITLE
Enter待ちはstd::cinで

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/othello-battler#12]
https://github.com/sapporocpp/othello-battler/blob/master/othello_runner.cpp#L57

```
std::cin.get();
```

あるいは

```
std::string line;
std::getline(std::cin, line);
```

で代用できる。

**Comment by maraigue** [comment]
それがあるのを失念してました。 https://github.com/sapporocpp/othello-battler/commit/effe69a1d28ad47f4783c01632e212f6c67b1875 にて対応しました。
