### ISSUE TITLE
popenよりもダイナミックロード推奨

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/othello-battler#13]
https://github.com/sapporocpp/othello-battler/blob/master/othello_runner.cpp#L76
プロセスたちあげよりも、共有ライブラリ or DLLがよいかと。

dlopen or LoadLibraryで関数直接呼び出せばいい。
Boost.DLL強く推奨。

```
$ ls
AI1.so AI2.so ...
$ ./othello_runner AI1 AI2
```

とかできるのでothello_runnerの再コンパイルとかも不要になるはず。

**Comment by usagi** [comment]
実行時の遅延dynamic loadはやめたほうがいい。さすがに今回は無いから今回使いたいなら止めないのだけど、windowsというOSのdynamic loadによるモジュールの実行時の遅延ロードは.dll間が別プロセスにでもいるかのような挙動を示すためにネットワークやOpenGLやデバイス制御などを伴った際に酷く面倒を伴ってしまう。

私も不本意ながらwindowsとかいうOSのそれが絡む可能性があるととたんに難易度が上がる問題をはらんでしまう可能性が生じるのでwindowsとかいうOSが絡みかねない、絡んでも構わないスタンスにおきたいならやめたといた方が良い。

実行後に`LoadLibrary`するのではなくて、翻訳時にシンボルテーブルをリンクしておき実行時に自動的にプロセスへリンクさせるのならばまだ複雑怪奇摩訶不思議に頭痛する事も少ないかもしれないけど、結局トラブルメーカーになる。

linuxだけならこんなこと微塵も言わないし寧ろやりましょうって言うんだけどね、私も。

**Comment by maraigue** [comment]
手間の面も考慮し、今回は見送りたいと思います。
なお、boostは使わない方針なので（勉強会の場で行うことを考えると、インストールに手間をかけるものは使いたくない）、boost.DLLも今回は利用しないことにしたいと思います。
