### ISSUE TITLE
<cstring>ではstd::stringを扱えずにエラーが出ると報告があった

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#21]
札幌C++勉強会#9当日に確か宮留さんから指摘があった。たぶんココらへんの話だと思う。
- https://github.com/sapporocpp/othello-battler/blob/1.0.0/othello_lib.hpp#L6
- https://github.com/sapporocpp/othello-battler/blob/1.0.0/othello_lib.hpp#L106

**Comment by maraigue** [comment]
これはミスです… 直しておきました。 https://github.com/sapporocpp/othello-battler/commit/812329e8563350eeeb8cccddb38ef4e93ad03832
なお新プログラムでは、（現時点で）std::stringは使っていないのでこの問題はありません。
