### ISSUE TITLE
windows では high_resolution_clock が system_clock と大差ない

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#22]
https://github.com/sapporocpp/othello-battler/blob/1.0.0/othello_runner.cpp#L110

MSVC++, mingw に関わらずwindowsでは std::chrono::high_resolution_clock の精度も分解能も低いのでHPET等を期待するなら

https://github.com/usagi/usagi/blob/master/include/usagi/chrono/windows_query_performance_counter_clock.hxx

こんなのが必要。

**Comment by maraigue** [comment]
今回は「極端な長考をしないでもらう」のが目的で導入したものなので、そこまでは考えなくていいところではありますが、頭にとどめておきます。
