### ISSUE TITLE
意図の伝わらないシンボル名を意図の伝わるシンボル名に変える

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#31]
ぱっとみてなんだかわからない命名でシンボル名を付けない。つけるとしてもせいぜい数行で使われ意図の解説が十二分に不要でもコードを読み易いような限定的な場合に制限する。

例えばこのtとか。特に初心者でなくとも突然出てきてなんだかわからない（わかるように読めというのではなく意図がわかるシンボル名にしておいた方が読む人のリソースを浪費しなくてすむ）。

https://github.com/sapporocpp/othello-battler/blob/master/othello_runner.cpp#L65

**Comment by maraigue** [comment]
ありがとうございます。新プログラムでは対応しました。
