### ISSUE TITLE
static_cast<int>(std::strtol(...)) --> std::stoi

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#34]
例えばここ

https://github.com/sapporocpp/othello-battler/blob/master/othello_runner.cpp#L47

これはモダンC++としては `std::stoi` だけでよいと思われる。

ref.: http://cpprefjp.github.io/reference/string/stoi.html

**Comment by maraigue** [comment]
これは単純に知りませんでした。今後使おうと思います。

**Comment by maraigue** [comment]
stoiは「mingwで」使えないという問題があるようです。
http://stackoverflow.com/questions/16132176/problems-with-stdstoi-not-working-on-mingw-gcc-4-7-2
私の普段の環境がmingwということもあるので、stoiはコメントアウトしてstrtolにします…。
