### ISSUE TITLE
use c++11 random

### ISSUE THREAD

**Issue by ignisan** [sapporocpp/othello-battler#7]
othello_runner.cpp:18

```
int rand_int(int n){
    int result;
    do{
        result = std::rand() / (RAND_MAX / n);
    }while(result >= n);
    return result;
}
```

// see std::uniform_int_distribution

**Comment by maraigue** [comment]
https://github.com/sapporocpp/othello-battler/commit/63c30685040e91df28637e57c7a542378b442178 にて対応しました。
