### ISSUE TITLE
C++11, 盤面の大きさ const int --> constexpr auto, ull

### ISSUE THREAD

**Issue by usagi** [sapporocpp/othello-battler#9]
https://github.com/sapporocpp/othello-battler/blob/master/othello_lib.hpp#L11

``` c++
    const int SIZE = 8; // 盤面の大きさ
```

↓こんな感じ？

``` c++
constexpr auto size = 8ull;
```

**Comment by maraigue** [comment]
一目見て、「単なる定数をconstではなくconstexprで定義する」ってどういう意味があるんだろう？って思ったのですが、ちゃんと意味があったのですね。
http://ja.stackoverflow.com/questions/1920/const%E3%81%A8constexpr%E3%81%AE%E9%81%95%E3%81%84

個人的にautoは極力使わない派なので、今回は採用を見送りたいと思います。
また、SIZEがsize_tなどではなくintになっているのは、座標値を表す用途にintを使ったほうが都合がよいためです（盤面の「1マス隣」などの計算を行うため、マイナスが使えないと都合が悪い）。

**Comment by maraigue** [comment]
constexprについては https://github.com/sapporocpp/othello-battler/commit/ebf5315523b5650e57ea275bf4ac74447c998718 で対応しました。
